#!/usr/bin/env python
from __future__ import absolute_import
import scss
import os

s = scss.Scss()

for fname in 'page.sass'.split():
    print "Processing %s..."%fname
    txt = s.compile(open(fname).read())
    open(os.path.join(os.pardir, 'static', fname.rsplit('.', 1)[0]+'.css'), 'w').write(txt)

