#!/usr/bin/env python
from __future__ import absolute_import
import scss
import os

s = scss.Scss()

for fname in 'page.scss'.split():
    print "Processing %s..."%fname
    txt = s.compile(open(fname).read())
    out = os.path.join(os.pardir, 'drink', 'static', fname.rsplit('.', 1)[0]+'.css')
    open(out, 'w').write(txt)
    print "Written %s."%out

